### ISSUE TITLE
Source Assessment

### ISSUE THREAD

**Issue by wimbledon** [XQS6LB3A/lyrics-module#3]
Out of the following sources, which one is most accurate and reliable?
Do you mind detailing the quality of each source?

- NetEase Music
- QQ Music
- Kugou Music
- Xiami Music
- TTPod
- Gecimi
- Syair
- ViewLyrics

**Comment by wimbledon** [comment]
@ddddxxx Would you mind putting additional information about each source?

**Comment by ddddxxx** [comment]
Sorry for delayed response. From my experience Netease and QQ music are the best as they are also the biggest music service provider in China.

**Comment by wimbledon** [comment]
Thanks for responding!
I noticed you made a change to the lyrics quality algorithm, so it should automatically pick out the best source right?

**Comment by ddddxxx** [comment]
You can use `quality` to pick out the best lyrics, not the best source. The algorithm is pretty awful I'd say, even after recent changes. But at least it rules out obviously wrong lyrics.

**Comment by wimbledon** [comment]
I noticed at Xiami source always errors and ViewLyrics always timeout after 60 seconds.
I suppose these two sources never work?

Btw, looks like LyricsSearchRequest's `timeout` property is not used in the actual request.

**Comment by ddddxxx** [comment]
Confirmed that Xiami and ViewLyrics are no longer working. I will remove them.

`LyricsSearchRequest.timeout` seems get lost during multiple refactorings. This bug is now tracked in #4. Thank you for reporting!

**Comment by ddddxxx** [comment]
Close as addressed all questions. Please feel free to open a new issue or reopen this one if you have further question.
