### ISSUE TITLE
`LyricsSearchRequest.timeout` is not used in the actual request

### ISSUE THREAD

**Issue by ddddxxx** [XQS6LB3A/lyrics-module#4]

**Comment by wimbledon** [comment]
Thanks for taking care of the timeout.
I noticed that some sources take more than 30 seconds FYI.

**Comment by ddddxxx** [comment]
I'm thinking about removing `timeout` all together. You can easily get this functionality with Combine operators:
```swift
let pub = provider.lyricsPublisher(request: req)
    .timeout(.seconds(10), scheduler: DispatchQueue.main.cx)
```

**Comment by wimbledon** [comment]
Yes, Combine is awesome.
however, as the consumer of your API, I did not know initially that it could that timeout can be that long.
I have already done something similar on my end to mitigate the long delay.
However, you might still set a reasonable default timeout for each source.

**Comment by ddddxxx** [comment]
The documentation of `URLSession` says:

> As a general rule, you should not use short timeout intervals. Instead, you should provide an easy way for the user to cancel a long-running operation.

So I guess it's ok to have default long timeout?

[`LyricsProvider.init` took `URLSession` before](https://github.com/ddddxxx/LyricsKit/blob/v0.7.0/Sources/Provider/ProviderProtocol.swift#L25). You can set default timeout using `URLSessionConfiguration`. But I think it doesn't worth the complexity of the interface so I removed it.

**Comment by wimbledon** [comment]
Sounds good to me!
Let's remove the timeout property then!
